name: Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"
      - uses: actions/checkout@v3
      - run: git config --global url.https://ci:$CI_GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url.https://ci:$CI_GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=5m